[build]
  # Directory to change to before starting build
  base = "frontend"
  
  # Build command
  command = "npm install && npm run build"
  
  # Directory where built files will be stored
  publish = "dist"
  
# Environment variables
[context.production.environment]
  # This variable will be replaced by the actual backend URL
  VITE_API_URL = "https://face-comparison-api.onrender.com"

# Redirect all URLs to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
