services:
  # Face Comparison API with ML dependencies - REQUIRES Python 3.9.18
  - type: web
    name: face-comparison-api
    runtime: python
    # CRITICAL: Must be Python 3.9.18 for TensorFlow compatibility
    pythonVersion: "3.9.18"
    buildCommand: |
      echo "Render Environment Info:" &&
      echo "Python runtime setting: $PYTHON_VERSION" &&
      echo "Available Python versions:" &&
      ls -la /opt/render/project/src/.venv/bin/python* 2>/dev/null || echo "No venv Python found yet" &&
      chmod +x build.sh && 
      ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    plan: free
    # Force specific region for better Python version control
    region: oregon
